os: osx
git:
  submodules: false
before_script:
   - chmod +x .travis.install
   - ./.travis.install
   - cd source  
script:
   -  make STARforMacStatic CXX=/usr/local/Cellar/gcc49/4.9.3/bin/g++-4.9
#   - make STARforMacStatic CXX=/usr/local/bin/g++-4.9
